language: csharp
solution: YFW.Net.sln
mono:
  - latest
git:
  depth: 300
script:
  - export EnableNuGetPackageRestore=false
  - mozroots --import --sync
  - bash travis-ci/autoversion.sh YFW.Net
  - bash travis-ci/autoversion.sh YFW.Net.Models
  - travis_retry mono .nuget/NuGet.exe restore YFW.Net.sln
  - xbuild /p:Configuration=Release YFW.Net.sln
  - xbuild /p:Configuration=Debug YFW.Net.sln
#  - sudo nunit-console -framework=4.0 ./QuadTrees.Tests/bin/Debug/QuadTrees.Tests.dll -exclude Integration,NotWorkingOnMono
  - travis_retry bash travis-ci/nuget-upload.sh